### ISSUE TITLE
BrewMonk Protective Add

### ISSUE THREAD

**Issue by geraint425** [johnnylam88/nerien-hekili-packs#3]
Hello. I really liked the implementation of your tank add-on. Thank you very much for your excellent work done. Good luck in this difficult path. But having tested Brewmonk I have encountered that defense abilities such as Zen Meditation Diffuse Magic Fortifying Brew, etc. are not used in the recommendation. If possible please add support for such strong defense abilities. That the addon also take them into account. This by the way works well in HeroRotation there defense kuladuns and strong defense kuldauns are well made with each other thereby strengthening the defense. And so once again I want to thank you for the cool realization of tanks.

**Comment by johnnylam88** [comment]
I'm planning on improving the monk defensive recommendations, but I simply haven't had the time to play the monk yet. However, now that Mythic+ is available, testing should be much easier.

**Comment by johnnylam88** [comment]
This should be improved significantly in 1.6.10.
