### ISSUE TITLE
[VENG DH] Fel-Scarred (hero talent tree)?

### ISSUE THREAD

**Issue by dannym314** [johnnylam88/nerien-hekili-packs#4]
I don't see any Fel-Scarred related support in the .simc file, only Aldrachi Reaver (hero talents). I was thinking about adding the Fel-Scarred talents and abilities in myself by reverse-engineering your code, but then I saw on your (2024-09-04) release notes that you had added support for VDH based on wowhead's tanking guide - and the wowhead tanking guide suggests Fel-Scarred.

Before I struggle through it myself, do you have the Fel-Scarred version anywhere? Or support coming for it?

Thanks.

**Comment by johnnylam88** [comment]
It should already support both hero talents based on the Wowhead guide. There seems to be a bug in Hekili currently that shows Fel-Scarred abilities even when they are not available, but I haven't had time to track that down yet.
